services:
  - type: web
    name: event-monolith-app
    env: node
    repo: https://github.com/Muntangarts/MonolithicEventApp.git
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ETHEREAL_USER
        sync: false
      - key: ETHEREAL_PASS
        sync: false